.TH "movies2hdd/gui.py" 3 "Mon Feb 17 2014" "Movies2HDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
movies2hdd/gui.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmovies2hdd\&.gui\&.Step1\fP"
.br
.ti -1c
.RI "class \fBmovies2hdd\&.gui\&.Step2\fP"
.br
.ti -1c
.RI "class \fBmovies2hdd\&.gui\&.Step3\fP"
.br
.ti -1c
.RI "class \fBmovies2hdd\&.gui\&.SeriesSelection\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBmovies2hdd\&.gui\fP"
.br
.in -1c
.SS "Constant Groups"

.in +1c
.ti -1c
.RI "\fBmovies2hdd\&.gui\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBmovies2hdd\&.gui\&.app\fP = QApplication(sys\&.argv)"
.br
.ti -1c
.RI "tuple \fBmovies2hdd\&.gui\&.msg\fP = QMessageBox()"
.br
.ti -1c
.RI "tuple \fBmovies2hdd\&.gui\&.movies2hdd\fP = Movies2HDD()"
.br
.ti -1c
.RI "tuple \fBmovies2hdd\&.gui\&.mainwindow\fP = QWizard()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Movies2HDD from the source code\&.
