.TH "movies2hdd/lbi.py" 3 "Sat Feb 1 2014" "Movies2HDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
movies2hdd/lbi.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBmovies2hdd\&.lbi\fP"
.br
.in -1c
.SS "Constant Groups"

.in +1c
.ti -1c
.RI "\fBmovies2hdd\&.lbi\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmovies2hdd\&.lbi\&.connect\fP"
.br
.ti -1c
.RI "def \fBmovies2hdd\&.lbi\&.disconnect\fP"
.br
.ti -1c
.RI "def \fBmovies2hdd\&.lbi\&.search\fP"
.br
.ti -1c
.RI "def \fBmovies2hdd\&.lbi\&.select\fP"
.br
.ti -1c
.RI "def \fBmovies2hdd\&.lbi\&.save\fP"
.br
.ti -1c
.RI "def \fBmovies2hdd\&.lbi\&.download\fP"
.br
.ti -1c
.RI "def \fBmovies2hdd\&.lbi\&.rename\fP"
.br
.ti -1c
.RI "def \fBmovies2hdd\&.lbi\&.convert\fP"
.br
.ti -1c
.RI "def \fBmovies2hdd\&.lbi\&.quit\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBmovies2hdd\&.lbi\&.Movies2HDD\fP = \fBmovies2hdd\&.Movies2HDD\fP()"
.br
.ti -1c
.RI "\fBmovies2hdd\&.lbi\&.ask\fP = raw_input"
.br
.ti -1c
.RI "tuple \fBmovies2hdd\&.lbi\&.answer\fP = int(ask('> '))"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Movies2HDD from the source code\&.
