.TH "md__r_e_a_d_m_e" 3 "Sat Feb 1 2014" "Movies2HDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- \fBmovies2hdd\fP 
A simple set of python scripts and libraries to work with movies\&. I use it with my DreamBox\&.
.IP "\(bu" 2
Homepage: http://elchi.github.io/movies2hdd (It is empty\&.)
.IP "\(bu" 2
Documentation of the API: http://elchi.github.io/movies2hdd/docs/html/ (generated using doxygen) 
.PP

.PP
.PP
Why should I use it?
.IP "\(bu" 2
It is written entirely in Python\&.
.IP "\(bu" 2
It supports both 2\&.7 \fIand\fP 3 \fIat the same time\fP\&. (!)
.IP "\(bu" 2
It is a class\&.
.IP "\(bu" 2
It is not finished\&. 
.PP

.PP
.PP
Features:
.IP "\(bu" 2
a CLI
.IP "  \(bu" 4
a line-based interface
.IP "  \(bu" 4
a GUI
.IP "  \(bu" 4
a simple movie converter (\&.ts to \&.mpg, will delete additional audio tracks!)
.PP

.IP "\(bu" 2
a library
.IP "  \(bu" 4
connects to a DreamBox via FTP
.IP "  \(bu" 4
searches for movies
.IP "  \(bu" 4
downloads movies
.IP "  \(bu" 4
filters meta data
.IP "  \(bu" 4
queries thetvdb\&.com
.IP "  \(bu" 4
converts the movies 
.PP

.PP

