.TH "movies2hdd.gui" 3 "Sat Feb 1 2014" "Movies2HDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
movies2hdd.gui \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBapp\fP = PySide\&.QtGui\&.QApplication(sys\&.argv)"
.br
.ti -1c
.RI "tuple \fBMovies2HDD\fP = \fBmovies2hdd\&.Movies2HDD\fP()"
.br
.ti -1c
.RI "tuple \fBmainwindow\fP = \fBMainWindow\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple movies2hdd\&.gui\&.app = PySide\&.QtGui\&.QApplication(sys\&.argv)"

.PP
Definition at line 34 of file gui\&.py\&.
.SS "tuple movies2hdd\&.gui\&.mainwindow = \fBMainWindow\fP()"

.PP
Definition at line 77 of file gui\&.py\&.
.SS "tuple movies2hdd\&.gui\&.Movies2HDD = \fBmovies2hdd\&.Movies2HDD\fP()"

.PP
Definition at line 38 of file gui\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Movies2HDD from the source code\&.
