.TH "movies2hdd.convert" 3 "Sat Feb 1 2014" "Movies2HDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
movies2hdd.convert \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBmovie\fP = sys\&.argv[1]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple movies2hdd\&.convert\&.movie = sys\&.argv[1]"

.PP
Definition at line 19 of file convert\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Movies2HDD from the source code\&.
